### ISSUE TITLE
Blockquote font too large

### ISSUE THREAD

**Issue by mgeier** [jupyter/nbviewer#604]
The font size for `<blockquote>` elements is awkwardly large:

```css
blockquote {
    font-size: 17.5px;
}
```

I didn't find this in the repo and I don't know where it comes from, but it seems to end up in http://nbviewer.jupyter.org/static/build/styles.css.

In the live Notebook as well as in the HTML-output of `nbconvert`, the font size is the same as the surrounding text, which looks decent:

```css
blockquote {
    font-size: inherit;
}
```

Could you please change this?
