### ISSUE TITLE
Nbviewer server not reachable

### ISSUE THREAD

**Issue by leon1995** [jupyter/nbviewer#815]
Hi guys.

Im using nbviewer and a jupyter notebook server behind a nginx proxy.

Docker-compose file:
```
version: '2'

services:
  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    volumes:
      - path:path
    environment:
      - VIRTUAL_HOST=jupyter.domain.toplvl
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=jupyter.domain.toplvl
      - LETSENCRYPT_EMAIL=mail@domain.toplvl
    networks:
      - proxy-tier
    restart: always

  nbviewer:
    image: jupyter/nbviewer
    container_name: nbviewer
    volumes:
      - path:path
    environment:
      - VIRRTUAL_HOST=nbviewer.domain.toplvl
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=nbviewer.domain.toplvl
      - LETSENCRYPT_EMAIL=mail@domain.toplvl
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: proxy-nginx
```
`$ docker-compose up -d` works and I get no errors.
But when I go to `nbviewer.domain.toplvl` I get a 503 error.
`jupyter.domain.toplvl` works.

I hope someone can help me :)
